apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      containers:
      - name: identity-server
        image: banty/clean.inventory.identity
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-server
spec:
  selector:
    app: identity-server
  ports:
  - port: 80
  type: LoadBalancer

    
