apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiving-api
spec:
  replicas: 0
  selector:
    matchLabels:
      name: receiving-api
  template:
    metadata:
      labels:
        name: receiving-api
    spec:
      containers:
        - image: banty/clean.inventory.receiving.api:latest
          name: receiving-api
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: receiving-api
spec:
  selector:
      name: receiving-api
  ports:
    - port: 80
  type: LoadBalancer
