apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-edge-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: mssql-data
      containers:
        - name: sql-server-local
          image: mcr.microsoft.com/azure-sql-edge:latest
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
            - name: MSSQL_AGENT_ENABLED
              value: "TRUE"
            - name: MSSQL_COLLATION
              value: "SQL_Latin1_General_CP1_CI_AS"
            - name: MSSQL_LCID
              value: "1033"
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001

---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-deployment
spec:
  selector:
    app: sql-server
  ports:
  - protocol: TCP
    port: 5433
    targetPort: 1433
    name: sql
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-internal
spec:
  selector:
    app: sql-server
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
    name: sql-server
  type: ClusterIP


          
          

            
    
